services:
  - type: web
    name: la-ruche
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run laruche:server
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA
        value: /tmp/toychain.data.json
